### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by offa**
Travis CI builds with GCC 6/7/8 and Clang 7/8.

### CODE REVIEW

**Comment by ahoarau** [comment]
Good to me ! @LouisCharlesC

**Comment by offa** [comment]
@LouisCharlesC do you have logged in on Travis already? There's no build status showing up.

**Comment by LouisCharlesC** [comment]
Just did, I actually have no idea how this works.
I updated the readme to show the build status, I think I got it right.
What should I do to turn that into a nice green "passing" ?

**Comment by offa** [comment]
The first build is going to update it! :-) And it seems your readme update was the first build. Perfect!

After your first login, travis will automatically detect all repositories with the travis yaml file and that's it.

**Pull request merged**
